#@base_url = http://localhost:8080/api
#@base_url = https://young-stream-32536.herokuapp.com/api


@base_url = https://testdarb1.herokuapp.com/api


#https://swapi.dev/api/planets/1/
###
#https://swapi.dev/api/people
###
{{base_url}}/guitar



###
POST {{base_url}}/guitar
Content-Type: application/json

{
  "name": "fender",
  "color": "white"
}


###
PUT {{base_url}}/guitar
Content-Type: application/json

{
  "name": "fender",
  "color": "toto"
}
###
POST {{base_url}}/guitar
Content-Type: application/json

{
  "name": "PRS",
  "color": "yellow"
}
###
DELETE {{base_url}}/guitar/fender