#@base_url = http://localhost:8080/api
#@base_url = https://young-stream-32536.herokuapp.com/api


@base_url = http://localhost:8080/amangousse/api


#https://swapi.dev/api/planets/1/
###
#https://swapi.dev/api/people
###
{{base_url}}/guitar
###
GET http://localhost:8080/api/guitar

###
POST http://localhost:8080/api/guitar
Content-Type: application/json

{
  "name": "lucas",
  "color": "black"
}


###
PUT http://localhost:8080/api/guitar
Content-Type: application/json

{
  "name": "lucas",
  "color": "toto"
}
###
POST {{base_url}}/guitar
Content-Type: application/json

{
  "name": "PRS",
  "color": "yellow"
}
###
DELETE {{base_url}}/guitar/fender